# Adapted from https://www.michaelpporter.com/2017/11/setting-up-docker4drupal-with-multiple-projects-on-mac-redo/

version: '2'
services:
  traefik:
    image: traefik:1.7.4-alpine
    restart: unless-stopped
    command: '-c /dev/null --web --docker --logLevel=DEBUG --defaultEntryPoints=''http'' --entryPoints="Name:http Address::80"'
    networks:
      - webgateway
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  webgateway:
    driver: bridge
